version: "3.9"
services:
  mongodb:
    image: mongo:7-jammy
    container_name: ${CONTAINER_NAME}
    restart: always
    ports:
      - "127.0.0.1:27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USER}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD}
    volumes:
      - db-volume-mongo:/data/db
    networks:
      - db-network-mongo

volumes:
  db-volume-mongo:

networks:
  db-network-mongo:
    external: true  